#
# Theme    : Tempohaus
# Version  : 1.0
# Author   : beingeorge
# Support  : hello@beingeorge.com
# 
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
#
# Refer Jekyll Documentation for more info. https://jekyllrb.com/docs/
#
#
# Site title
title: "Typography Studio"
#

# A description of your site
description: "A book design and typesetting practice based in Melbourne, Australia."

# The subpath of your site
# Leave baseurl blank when you run it in local
# baseurl:
baseurl: https://studiotype.github.io/tempohaus.studio


# In this theme static CSS is not used. 
sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "http://beingeorge.com"

# Site navigation - list your url with text and the url (Path)
navigation:
- text: Book Design
  url: /books.html
- text: Typesetting
  url: /typesetting.html
- text: Contact
  url: /contact.html

permalink: /typesetting/

# Author Info
author_name: "Edward tempohaus"
author_bio: "Edward tempohaus is often compared to animals, implying that he is not a fully evolved human being."
author_url:  "http://beingeorge.com"
author_image: author.jpg

# Social links
facebook_username: "username"
twitter_username: "username"
googleplus_username: "username"
codepen_username: "username"
dribbble_uername: "username"
instagram_username: "username"
pinterest_username: "username"
linkedin_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/pages/page:num/'
plugins: [jekyll-paginate]

